import '@/database/db'
import '@/modules/general/theme/theme.signals'
import '@/modules/settings/notification.signals'
import '@/modules/settings/oldDBMigration.signals'
import '@/modules/settings/language.signals'
import '@/modules/settings/currency.signals'
import '@/modules/settings/tax.signals'