@startuml
'https://plantuml.com/class-diagram

hide circle
hide empty members

class MetersEntity {
   name: string
   identification: string

   'Configuration
   digits: int
   unit: string
   areValuesDepleting: boolean
   isActive: boolean

   'Foreign keys
   contract: ContractEntity
}

class ContractEntity {
   name: string
   identification: string
   pricePerUnit: double
}

MetersEntity "*" -- "1" ContractEntity

class MeasurementsEntity {
   value: double
   timestamp: Date

   'Foreign keys
   meter: MetersEntity
}

MetersEntity "1" -- "*" MeasurementsEntity

class Settings {
   databaseVersion: int

   shouldRemindUser: boolean
   reminderInterval: "daily" | "weekly" | "monthly"
   reminderTime: {hour: int, minute: int} | {hour: int, minute: int, day: int} | {hour: int, minute: int, day: int, week: int}

   shouldSendBackupMail: boolean
   backupMailAddress: string
   everyXMonths: int
   mailDay: int
   mailHour: int
   mailMinute: int
}

@enduml
